module.exports = {
    docs: {
        // 'Getting Started': ['getting-started/01-introduction'],
        Introduction: ['01-introduction/01-introduction-platformer-console'],
        'Administration and Access Management': [
            '02-administration/01-resource-hierachies',
            '02-administration/02-organizations',
            '02-administration/03-billing-accounts',
            '02-administration/04-projects',
            '02-administration/05-iam',
            '02-administration/06-service-accounts',
            '02-administration/07-audit-logs',
        ],
        'Connecting Kubernetes Clusters': [
            '03-clusters/01-cluster-introduction',
            '03-clusters/02-cluster-requirements',
            '03-clusters/03-connecting-clusters',
            '03-clusters/04-troubleshooting',
        ],
        'Managing Environments': [
            '04-environments/01-env-introduction',
            '04-environments/02-creating-environments',
            '04-environments/03-multi-cluster-environments',
            '04-environments/04-environment-namespaces',
            '04-environments/05-configs-and-secrets',
            '04-environments/06-activity-logs',
        ],
        Integrations: [
            '05-integrations/01-container-registry-integration',
            '05-integrations/02-image-collections',
        ],
        'Deploying and managing Applications and Workloads': [
            '06-applications/01-applications-overview',
            '06-applications/02-creating-applications',
            '06-applications/03-webhooks',
            '06-applications/04-configs-and-secrets',
            '06-applications/05-scaling',
            '06-applications/06-healthchecks',
            '06-applications/07-ingress',
            '06-applications/08-advanced-yaml',
            '06-applications/09-volumes',
        ],
        // Tutorials: ['styleguide'],
        // Guides: ['styleguide', '01-organizations', '02-projects'],
        // 'API Reference': ['api-reference/cli'],
    },
};
